services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Docker@1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - my-shared-network

  web:
    build:
      context: .    # Path to project folder
      dockerfile: SpendSmart/Dockerfile      # Relative to project folder
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db;Database=SpendSmartDB;User=sa;Password=Docker@1234;TrustServerCertificate=True;
    depends_on:
      - db
    ports:
      - "9090:8080"
    networks:
      - my-shared-network

volumes:
  sql_data:
  networks:

networks:
  my-shared-network:
  external: true